name: Release build Manual

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      release_tag_name:
        description: 'Release tag name (only effective when dry_run = false, example v1.2.3)'
        required: false
        type: string
      build_android:
        description: Build Android platform artifacts.
        required: true
        type: boolean
        default: true
      build_ios:
        description: Build iOS platform artifacts.
        required: true
        type: boolean
        default: true
      build_linux:
        description: Build Linux platform artifacts.
        required: true
        type: boolean
        default: true
      build_macos:
        description: Build MacOS platform artifacts.
        required: true
        type: boolean
        default: true
      build_windows:
        description: Build Windows platform artifacts.
        required: true
        type: boolean
        default: true
      dry_run:
        description: Dry run, do NOT create release and NOT upload to release page.
        required: true
        type: boolean
        default: true

env:
  CI_FLUTTER_VERSION: "3.47.4"
  CI_RUST_VERSION: "1.83.0"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  create-release:
    name: Create GitHub Release
    if: ${{ github.event_name == 'workflow_dispatch' && !inputs.dry_run && inputs.release_tag_name != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PRERELEASE: ${{ contains(inputs.release_tag_name, '-') }}
    outputs:
      release-id: ${{ steps.create_release.outputs.id }}
      release-upload-url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.release_tag_name }}
          prerelease: ${{ env.PRERELEASE }}
          allowUpdates: true
          omitPrereleaseDuringUpdate: true
          body: "Built from manual Release build workflow"

  build-linux:
    name: Build Linux
    if: ${{ github.event_name == 'pull_request' || inputs.build_linux }}
    runs-on: ubuntu-latest
    needs: [create-release]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}
          cache: true
      - run: |
          sudo apt update -y
          sudo apt install -y ninja-build libgtk-3-dev sqlite3 libsqlite3-dev
      - name: Precompile
        run: |
          git submodule update --init --recursive --force
          flutter pub get
      - name: Build Linux
        if: ${{ github.event_name == 'pull_request' || inputs.build_linux }}
        run: flutter build linux --release
      - name: Pre Packing
        if: ${{ github.event_name == 'pull_request' || inputs.build_linux }}
        run: |
          pushd build/linux/x64/release/
          mv bundle Hikari_Novel
          popd
      - name: Pack Linux tarball
        if: ${{ github.event_name == 'pull_request' || inputs.build_linux }}
        uses: thedoctor0/zip-release@master
        with:
          type: "tar"
          filename: Hikari_Novel-linux.tar.gz
          directory: build/linux/x64/release/
          path: Hikari_Novel
      - name: Upload Linux artifacts to workflow artifact
        if: ${{ github.event_name == 'pull_request' || (!inputs.dry_run && inputs.build_linux) }}
        uses: actions/upload-artifact@v4
        with:
          name: Hikari_Novel-linux-tarball
          path: build/linux/x64/release/Hikari_Novel-linux.tar.gz
      - name: Upload to GitHub Release
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.dry_run && inputs.build_linux && inputs.release_tag_name != '' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBody: true
          omitBodyDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: build/linux/x64/release/Hikari_Novel-linux.tar.gz
          tag: ${{ inputs.release_tag_name }}

  build-android:
    name: Build Android
    if: ${{ github.event_name == 'pull_request' || inputs.build_android }}
    runs-on: ubuntu-latest
    needs: [create-release]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}
          cache: true
      - run: |
          sudo apt update -y
          sudo apt install -y ninja-build
          git submodule update --init --recursive --force
      - name: Precompile
        run: |
          flutter pub get
      # ========= 签名部分，不需要签名直接注释掉这整块 =========
      # - name: Setup Android sign key
      #   if: ${{ github.event_name == 'pull_request' || inputs.build_android }}
      #   run: |
      #     echo '${{ secrets.KEYSTORE }}' | base64 --decode > android/app/key.jks
      #     echo '${{ secrets.KEY_PROPERTIES }}' > android/key.properties
      - name: Build Android split per abi
        if: ${{ github.event_name == 'pull_request' || inputs.build_android }}
        run: |
          flutter build apk --release --split-per-abi
      - name: Rename APK
        if: ${{ github.event_name == 'pull_request' || inputs.build_android }}
        run: |
          pushd build/app/outputs/flutter-apk/
          mv app-arm64-v8a-release.apk Hikari_Novel-arm64_v8a.apk
          mv app-armeabi-v7a-release.apk Hikari_Novel-armeabi_v7a.apk
          popd
      - name: Upload Android artifacts to workflow artifact
        if: ${{ github.event_name == 'pull_request' || (!inputs.dry_run && inputs.build_android) }}
        uses: actions/upload-artifact@v4
        with:
          name: Hikari_Novel-apk
          path: |
            build/app/outputs/flutter-apk/Hikari_Novel-arm64_v8a.apk
            build/app/outputs/flutter-apk/Hikari_Novel-armeabi_v7a.apk
      - name: Upload to GitHub Release
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.dry_run && inputs.build_android && inputs.release_tag_name != '' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBody: true
          omitBodyDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: |
            build/app/outputs/flutter-apk/Hikari_Novel-arm64_v8a.apk
            build/app/outputs/flutter-apk/Hikari_Novel-armeabi_v7a.apk
          tag: ${{ inputs.release_tag_name }}

  build-windows:
    name: Build Windows
    if: ${{ github.event_name == 'pull_request' || inputs.build_windows }}
    runs-on: windows-latest
    needs: [create-release]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}
      - name: Precompile
        shell: pwsh
        run: |
          git submodule update --init --recursive --force
          flutter pub get
      - name: Build Windows
        env:
          # 修复MSVC STL1011 coroutine废弃报错
          CXXFLAGS: -D_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS
        run: flutter build windows --release
      - name: Pre Packing
        shell: pwsh
        run: |
          cd build/windows/x64/runner
          Rename-Item Release Hikari_Novel
          cd ../../../../
      - name: Pack Windows zip
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: Hikari_Novel-windows.zip
          directory: build/windows/x64/runner
          path: Hikari_Novel
      - name: Upload Windows artifacts to workflow artifact
        if: ${{ github.event_name == 'pull_request' || (!inputs.dry_run && inputs.build_windows) }}
        uses: actions/upload-artifact@v4
        with:
          name: Hikari_Novel-windows-tarball
          path: build/windows/x64/runner/Hikari_Novel-windows.zip
      - name: Upload to GitHub Release
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.dry_run && inputs.build_windows && inputs.release_tag_name != '' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBody: true
          omitBodyDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: build/windows/x64/runner/Hikari_Novel-windows.zip
          tag: ${{ inputs.release_tag_name }}

  build-macos-and-ios:
    name: Build MacOS and iOS
    if: ${{ github.event_name == 'pull_request' || inputs.build_macos || inputs.build_ios }}
    runs-on: macos-latest
    needs: [create-release]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}
          cache: true
      - name: Precompile
        run: |
          git submodule update --init --recursive --force
          flutter pub get
      - name: Build MacOS
        if: ${{ github.event_name == 'pull_request' || inputs.build_macos }}
        run: |
          flutter build macos --release
      - name: Upload MacOS artifacts to workflow artifact
        if: ${{ github.event_name == 'pull_request' || (!inputs.dry_run && inputs.build_macos) }}
        uses: actions/upload-artifact@v4
        with:
          name: Hikari_Novel-macos-app
          path: build/macos/Build/Products/Release/Hikari\ Novel.app
      - name: Upload macOS to GitHub Release
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.dry_run && inputs.build_macos && inputs.release_tag_name != '' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBody: true
          omitBodyDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: build/macos/Build/Products/Release/Hikari\ Novel.app
          tag: ${{ inputs.release_tag_name }}
      - name: Build iOS ipa
        if: ${{ github.event_name == 'pull_request' || inputs.build_ios }}
        run: |
          flutter build ios --release --no-codesign
      - name: Packing IPA
        if: ${{ github.event_name == 'pull_request' || inputs.build_ios }}
        run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload
          zip -r9 Hikari_Novel.ipa Payload
      - name: Upload iOS artifacts to workflow artifact
        if: ${{ github.event_name == 'pull_request' || (!inputs.dry_run && inputs.build_ios) }}
        uses: actions/upload-artifact@v4
        with:
          name: Hikari_Novel-ios-tarball
          path: Hikari_Novel.ipa
      - name: Upload iOS to GitHub Release
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.dry_run && inputs.build_ios && inputs.release_tag_name != '' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBody: true
          omitBodyDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: Hikari_Novel.ipa
          tag: ${{ inputs.release_tag_name }}
